
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: []
            client-secret: []
            scope:
              - email
              - profile

  spring:
    # DB ?? ?? ?? => localhost:3306
    datasource:
      url: jdbc:mysql://localhost:3306/[DB??]?serverTimezone=Asia/Seoul
      username: root
      password: KimHanJu080210@
      driver-class-name: com.mysql.cj.jdbc.Driver

    # JPA ??
    jpa:
      hibernate:
        ddl-auto: create # application ? ?? ??? create, ???? none ?? ????
      show-sql: true
